//
//  File.swift
//  
//
//  Created by Paul MacRory on 25/11/2019.
//

import Foundation

public enum FitManufacturer: UInt16 {
  case invalid                                                 = 0xFFFF
  case garmin                                                  = 1
  case garmin_fr405_antfs                                      = 2 // do not use.  used by fr405 for antfs man id.
  case zephyr                                                  = 3
  case dayton                                                  = 4
  case idt                                                     = 5
  case srm                                                     = 6
  case quarq                                                   = 7
  case ibike                                                   = 8
  case saris                                                   = 9
  case spark_hk                                                = 10
  case tanita                                                  = 11
  case echowell                                                = 12
  case dynastream_oem                                          = 13
  case nautilus                                                = 14
  case dynastream                                              = 15
  case timex                                                   = 16
  case metrigear                                               = 17
  case xelic                                                   = 18
  case beurer                                                  = 19
  case cardiosport                                             = 20
  case a_and_d                                                 = 21
  case hmm                                                     = 22
  case suunto                                                  = 23
  case thita_elektronik                                        = 24
  case gpulse                                                  = 25
  case clean_mobile                                            = 26
  case pedal_brain                                             = 27
  case peaksware                                               = 28
  case saxonar                                                 = 29
  case lemond_fitness                                          = 30
  case dexcom                                                  = 31
  case wahoo_fitness                                           = 32
  case octane_fitness                                          = 33
  case archinoetics                                            = 34
  case the_hurt_box                                            = 35
  case citizen_systems                                         = 36
  case magellan                                                = 37
  case osynce                                                  = 38
  case holux                                                   = 39
  case concept2                                                = 40
  case one_giant_leap                                          = 42
  case ace_sensor                                              = 43
  case brim_brothers                                           = 44
  case xplova                                                  = 45
  case perception_digital                                      = 46
  case bf1systems                                              = 47
  case pioneer                                                 = 48
  case spantec                                                 = 49
  case metalogics                                              = 50
  case _4iiiis                                                  = 51
  case seiko_epson                                             = 52
  case seiko_epson_oem                                         = 53
  case ifor_powell                                             = 54
  case maxwell_guider                                          = 55
  case star_trac                                               = 56
  case breakaway                                               = 57
  case alatech_technology_ltd                                  = 58
  case mio_technology_europe                                   = 59
  case rotor                                                   = 60
  case geonaute                                                = 61
  case id_bike                                                 = 62
  case specialized                                             = 63
  case wtek                                                    = 64
  case physical_enterprises                                    = 65
  case north_pole_engineering                                  = 66
  case bkool                                                   = 67
  case cateye                                                  = 68
  case stages_cycling                                          = 69
  case sigmasport                                              = 70
  case tomtom                                                  = 71
  case peripedal                                               = 72
  case wattbike                                                = 73
  case moxy                                                    = 76
  case ciclosport                                              = 77
  case powerbahn                                               = 78
  case acorn_projects_aps                                      = 79
  case lifebeam                                                = 80
  case bontrager                                               = 81
  case wellgo                                                  = 82
  case scosche                                                 = 83
  case magura                                                  = 84
  case woodway                                                 = 85
  case elite                                                   = 86
  case nielsen_kellerman                                       = 87
  case dk_city                                                 = 88
  case tacx                                                    = 89
  case direction_technology                                    = 90
  case magtonic                                                = 91
  case _1partcarbon                                             = 92
  case inside_ride_technologies                                = 93
  case sound_of_motion                                         = 94
  case stryd                                                   = 95
  case icg                                                     = 96 // indoorcycling group
  case mipulse                                                 = 97
  case bsx_athletics                                           = 98
  case look                                                    = 99
  case campagnolo_srl                                          = 100
  case body_bike_smart                                         = 101
  case praxisworks                                             = 102
  case limits_technology                                       = 103 // limits technology ltd.
  case topaction_technology                                    = 104 // topaction technology inc.
  case cosinuss                                                = 105
  case fitcare                                                 = 106
  case magene                                                  = 107
  case giant_manufacturing_co                                  = 108
  case tigrasport                                              = 109 // tigrasport
  case salutron                                                = 110
  case technogym                                               = 111
  case bryton_sensors                                          = 112
  case latitude_limited                                        = 113
  case soaring_technology                                      = 114
  case igpsport                                                = 115
  case thinkrider                                              = 116
  case gopher_sport                                            = 117
  case waterrower                                              = 118
  case orangetheory                                            = 119
  case inpeak                                                  = 120
  case kinetic                                                 = 121
  case johnson_health_tech                                     = 122
  case polar_electro                                           = 123
  case seesense                                                = 124
  case nci_technology                                          = 125
  case iqsquare                                                = 126
  case leomo                                                   = 127
  case ifit_com                                                = 128
  case development                                             = 255
  case healthandlife                                           = 257
  case lezyne                                                  = 258
  case scribe_labs                                             = 259
  case zwift                                                   = 260
  case watteam                                                 = 261
  case recon                                                   = 262
  case favero_electronics                                      = 263
  case dynovelo                                                = 264
  case strava                                                  = 265
  case precor                                                  = 266 // amer sports
  case bryton                                                  = 267
  case sram                                                    = 268
  case navman                                                  = 269 // mitac global corporation (mio technology)
  case cobi                                                    = 270 // cobi gmbh
  case spivi                                                   = 271
  case mio_magellan                                            = 272
  case evesports                                               = 273
  case sensitivus_gauge                                        = 274
  case podoon                                                  = 275
  case life_time_fitness                                       = 276
  case falco_e_motors                                          = 277 // falco emotors inc.
  case minoura                                                 = 278
  case cycliq                                                  = 279
  case luxottica                                               = 280
  case trainer_road                                            = 281
  case the_sufferfest                                          = 282
  case fullspeedahead                                          = 283
  case virtualtraining                                         = 284
  case feedbacksports                                          = 285
  case omata                                                   = 286
  case vdo                                                     = 287
  case magneticdays                                            = 288
  case hammerhead                                              = 289
  case kinetic_by_kurt                                         = 290
  case shapelog                                                = 291
  case dabuziduo                                               = 292
  case jetblack                                                = 293
  case coros                                                   = 294
  case virtugo                                                 = 295
  case velosense                                               = 296
  case cycligentinc                                            = 297
  case trailforks                                              = 298
  case mahle_ebikemotion                                       = 299
  case actigraphcorp                                           = 5759
}
